# Generated by Django 4.1.2 on 2022-10-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_artiste_stage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiste',
            name='stage_name',
        ),
    ]
