# Generated by Django 4.1.2 on 2022-10-29 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_alter_song_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='release_date',
        ),
    ]
