# Generated by Django 4.1.2 on 2022-10-29 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_remove_song_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
