# Generated by Django 4.1.2 on 2022-10-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_alter_song_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.CharField(max_length=40),
        ),
    ]
