# Generated by Django 4.1.2 on 2022-10-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_alter_song_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
