# Generated by Django 4.1.2 on 2022-10-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0013_alter_lyrics_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
