# Generated by Django 4.1.2 on 2022-10-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0014_alter_lyrics_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lyrics',
            new_name='Lyric',
        ),
    ]
