# Generated by Django 4.1.3 on 2022-11-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0016_alter_song_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song_id',
            new_name='song_name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste_id',
            new_name='artiste_name',
        ),
    ]
